network:
  version: 2
  renderer: networkd
  
  ethernets:  
    enp2s0:
      dhcp4: false
  
  bridges:
    br-ex:
      interfaces:
        - enp2s0
      addresses:
        - 192.168.1.14/24
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8